#!/usr/bin/env bash
# ============================================
# Docker Image Import Script (Linux)
# Auto-generated by build_and_export.bat
# ============================================

set -e
set -o pipefail

echo "======================================"
echo "  Nano Banana Editor - Image Import"
echo "======================================"
echo ""

# Image info (placeholders replaced by build script)
IMAGE_NAME="__IMAGE_NAME__"
IMAGE_TAG="__IMAGE_TAG__"
IMAGE_LATEST="__IMAGE_LATEST__"
TAR_FILE="__TAR_FILE__"

# Check tar file exists
if [ ! -f "$TAR_FILE" ]; then
    echo "[ERROR] Image file not found: $TAR_FILE"
    echo "Please ensure the image file is in the current directory."
    exit 1
fi

echo "[1/4] Checking Docker service..."
if ! docker info >/dev/null 2>&1; then
    echo "[ERROR] Docker service is not running."
    echo "Please start Docker first: systemctl start docker"
    exit 1
fi
echo "Docker service is running"
echo ""

echo "[2/4] Cleaning up old images..."
OLD_IMAGE_COUNT=$(docker images "$IMAGE_NAME" -q 2>/dev/null | wc -l)
if [ "$OLD_IMAGE_COUNT" -gt 0 ]; then
    echo "Found old images:"
    docker images "$IMAGE_NAME"
    echo ""
    echo "Stopping and removing related containers..."

    # Stop containers using this image
    CONTAINERS=$(docker ps -a -q --filter "ancestor=$IMAGE_NAME" 2>/dev/null || true)
    if [ -n "$CONTAINERS" ]; then
        docker stop $CONTAINERS 2>/dev/null || true
        docker rm $CONTAINERS 2>/dev/null || true
    fi

    # Remove old images
    docker rmi -f $(docker images "$IMAGE_NAME" -q | uniq) 2>/dev/null || true
    echo "Old images removed"
else
    echo "No old images found"
fi
echo ""

echo "[3/4] Loading new image..."
echo "File: $TAR_FILE"
if ! docker load -i "$TAR_FILE"; then
    echo "[ERROR] Image import failed"
    exit 1
fi
echo ""

echo "[4/4] Verifying import..."
echo "Current images:"
docker images "$IMAGE_NAME"
echo ""

echo "======================================"
echo "  Image import completed!"
echo "======================================"
echo ""
echo "Image tag: $IMAGE_TAG"
echo "Latest tag: $IMAGE_LATEST"
echo ""
echo "Next steps:"
echo ""
echo "1. Configure environment:"
echo "   cp .env.prod.example .env.prod"
echo "   vim .env.prod"
echo ""
echo "2. Start service:"
echo "   docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo "3. View logs:"
echo "   docker-compose -f docker-compose.prod.yml logs -f"
echo ""
